language: android

sudo: true

env:
  global:
  - MALLOC_ARENA_MAX=2

android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

notifications:
  email: false